---
#
# see the common charts values definition for all available options:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common
#

# defines the image to use
image:
  repository: ghcr.io/weblyzard/inscriptis
  tag: 2.3.0
  pullPolicy: Always

# defines the replication and update strategy
controller:
  strategy: RollingUpdate
  replicas: 2
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

# defines the resource to be allocated by the pod
resources:
  limits:
     memory: 1024Mi
  requests:
     memory: 1024Mi

# defines the services created for this application.
service:
  main:
    enabled: true
    type: ClusterIP
    ports:
      http:
        port: 5000
        targetPort: 5000
        protocol: HTTP


# defines the ingress created for this application
ingress:
  main:  
    enabled: true
    annotations: {}
    hosts:
      - host: inscriptis.cluster.local
        paths:
        - path: /
        service:
          name: inscriptis
          port: 5000
    tls: {}